# Generated by Django 5.2.6 on 2025-10-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
