# Generated by Django 5.2.6 on 2025-10-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bag', 'Bag'), ('jersey', 'Jersey'), ('exclusive', 'Exclusive'), ('boots', 'Boots'), ('accessories', 'Accessories'), ('hoodie', 'Hoodie')], default='update', max_length=20),
        ),
    ]
